name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'infrastructure/cdk/**'
      - '.github/workflows/deploy-infrastructure.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prd

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: dev
            github_environment: develop
            branch_condition: ${{ github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'dev' }}
          - environment: prd
            github_environment: main
            branch_condition: ${{ github.ref == 'refs/heads/main' || github.event.inputs.environment == 'prd' }}
    
    environment: ${{ matrix.github_environment }}
    if: ${{ matrix.branch_condition }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK dependencies
        working-directory: infrastructure/cdk
        run: npm ci

      - name: Build CDK
        working-directory: infrastructure/cdk
        run: npm run build

      - name: CDK Bootstrap (if needed)
        working-directory: infrastructure/cdk
        run: |
          if ! aws cloudformation describe-stacks --stack-name CDKToolkit --region ${{ env.AWS_REGION }} > /dev/null 2>&1; then
            npm run cdk bootstrap
          fi

      - name: Deploy Certificate Stack
        working-directory: infrastructure/cdk
        run: npm run cdk deploy CertificateStack-${{ matrix.environment }} --require-approval never

      - name: Deploy Main Stack
        working-directory: infrastructure/cdk
        run: npm run cdk deploy DevToolsStack-${{ matrix.environment }} --require-approval never

      - name: Output deployment info
        working-directory: infrastructure/cdk
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ matrix.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- Region: ${{ env.AWS_REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "- Deployed stacks:" >> $GITHUB_STEP_SUMMARY
          echo "  - CertificateStack-${{ matrix.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "  - DevToolsStack-${{ matrix.environment }}" >> $GITHUB_STEP_SUMMARY